// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface AboutDescriptionStoryblok {
  title?: string;
  content?: RichtextStoryblok;
  component: "about-description";
  _uid: string;
  [k: string]: any;
}

export interface AboutPageStoryblok {
  title?: string;
  content?: RichtextStoryblok;
  component: "about-page";
  _uid: string;
  [k: string]: any;
}

export interface AllInformationPostsStoryblok {
  component: "all-information-posts";
  _uid: string;
  [k: string]: any;
}

export interface AllProfilesStoryblok {
  component: "all-profiles";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface ConfigStoryblok {
  items?: MenuLinkStoryblok[];
  hero_image?: AssetStoryblok;
  hero_title?: string;
  hero_content?: string;
  component: "config";
  _uid: string;
  [k: string]: any;
}

export interface ContactPageStoryblok {
  meta?: any;
  titles?: any;
  title?: string;
  email?: string;
  telefon?: string;
  links?: MenuLinkStoryblok[];
  email_title?: string;
  telefon_title?: string;
  links_title?: string;
  meta_title?: string;
  meta_description?: string;
  component: "contact-page";
  _uid: string;
  [k: string]: any;
}

export interface EntryStoryblok {
  value?: string;
  component: "entry";
  _uid: string;
  [k: string]: any;
}

export interface TableStoryblok {
  thead: {
    _uid: string;
    value?: string;
    component: number;
    [k: string]: any;
  }[];
  tbody: {
    _uid: string;
    body: {
      _uid?: string;
      value?: string;
      component?: number;
      [k: string]: any;
    }[];
    component: number;
    [k: string]: any;
  }[];
  [k: string]: any;
}

export interface FeatureStoryblok {
  name: string;
  image: AssetStoryblok;
  gender: string;
  birthdate: string;
  price?: string;
  table?: TableStoryblok;
  group?: any;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  [k: string]: any;
}[];

export interface GalleryStoryblok {
  images?: MultiassetStoryblok;
  component: "gallery";
  _uid: string;
  [k: string]: any;
}

export interface GalleryPageStoryblok {
  meta?: any;
  title?: string;
  meta_title?: string;
  meta_description?: string;
  gallery?: MultiassetStoryblok;
  component: "gallery-page";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | AboutDescriptionStoryblok
    | AboutPageStoryblok
    | AllInformationPostsStoryblok
    | AllProfilesStoryblok
    | ConfigStoryblok
    | ContactPageStoryblok
    | EntryStoryblok
    | FeatureStoryblok
    | GalleryStoryblok
    | GalleryPageStoryblok
    | GridStoryblok
    | HomePageStoryblok
    | ImageLinkStoryblok
    | InformationPostStoryblok
    | MenuLinkStoryblok
    | PageStoryblok
    | ProfileStoryblok
    | RelativeStoryblok
    | TeaserStoryblok
    | ValuesListStoryblok
  )[];
  title?: string;
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface HomePageStoryblok {
  meta?: any;
  title?: string;
  content?: string;
  block?: (
    | AboutDescriptionStoryblok
    | AboutPageStoryblok
    | AllInformationPostsStoryblok
    | AllProfilesStoryblok
    | ConfigStoryblok
    | ContactPageStoryblok
    | EntryStoryblok
    | FeatureStoryblok
    | GalleryStoryblok
    | GalleryPageStoryblok
    | GridStoryblok
    | HomePageStoryblok
    | ImageLinkStoryblok
    | InformationPostStoryblok
    | MenuLinkStoryblok
    | PageStoryblok
    | ProfileStoryblok
    | RelativeStoryblok
    | TeaserStoryblok
    | ValuesListStoryblok
  )[];
  meta_title?: string;
  meta_description?: string;
  cta_list?: (
    | AboutDescriptionStoryblok
    | AboutPageStoryblok
    | AllInformationPostsStoryblok
    | AllProfilesStoryblok
    | ConfigStoryblok
    | ContactPageStoryblok
    | EntryStoryblok
    | FeatureStoryblok
    | GalleryStoryblok
    | GalleryPageStoryblok
    | GridStoryblok
    | HomePageStoryblok
    | ImageLinkStoryblok
    | InformationPostStoryblok
    | MenuLinkStoryblok
    | PageStoryblok
    | ProfileStoryblok
    | RelativeStoryblok
    | TeaserStoryblok
    | ValuesListStoryblok
  )[];
  main_image?: AssetStoryblok;
  component: "home-page";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
      [k: string]: any;
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
      [k: string]: any;
    };

export interface ImageLinkStoryblok {
  cta_text?: string;
  image?: AssetStoryblok;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "image-link";
  _uid: string;
  [k: string]: any;
}

export interface InformationPostStoryblok {
  meta?: any;
  title?: string;
  content?: RichtextStoryblok;
  meta_title?: string;
  meta_description?: string;
  component: "information-post";
  _uid: string;
  [k: string]: any;
}

export interface MenuLinkStoryblok {
  link_name: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "menu_link";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  meta?: any;
  title?: string;
  body?: (
    | AboutDescriptionStoryblok
    | AboutPageStoryblok
    | AllInformationPostsStoryblok
    | AllProfilesStoryblok
    | ConfigStoryblok
    | ContactPageStoryblok
    | EntryStoryblok
    | FeatureStoryblok
    | GalleryStoryblok
    | GalleryPageStoryblok
    | GridStoryblok
    | HomePageStoryblok
    | ImageLinkStoryblok
    | InformationPostStoryblok
    | MenuLinkStoryblok
    | PageStoryblok
    | ProfileStoryblok
    | RelativeStoryblok
    | TeaserStoryblok
    | ValuesListStoryblok
  )[];
  meta_title?: string;
  meta_description?: string;
  content_absent?: string;
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface ProfileStoryblok {
  field_titles?: any;
  gender_title?: string;
  birthdate_title?: string;
  price_title?: string;
  description_title?: string;
  parents_title?: string;
  children_title?: string;
  link_title?: string;
  gallery_title?: string;
  title: string;
  image?: AssetStoryblok;
  gender: "" | "female" | "male" | "weiblich" | "männlich" | "женский" | "мужской";
  birthdate?: string;
  price?: string;
  description?: RichtextStoryblok;
  parents?: RelativeStoryblok[];
  children?: (ChildStoryblok | RelativeStoryblok)[];
  gallery?: MultiassetStoryblok;
  component: "profile";
  _uid: string;
  [k: string]: any;
}

export interface RelativeStoryblok {
  name?: string;
  image?: AssetStoryblok;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  link_title?: string;
  component: "relative";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}

export interface ValuesListStoryblok {
  title?: string;
  values?: EntryStoryblok[];
  component: "values-list";
  _uid: string;
  [k: string]: any;
}
